### ISSUE TITLE
Docker + 개인 도메인 써서 서버 열어봤습니다

### ISSUE THREAD

**Issue by krome0** [krome0/universal-kiosk#13]
<img width="1920" alt="스크린샷 2022-12-09 오전 1 40 50" src="https://user-images.githubusercontent.com/37375701/206512238-3675c7ad-2808-46d1-9c58-b8230252e784.png">

일단 잘 열리는 것 같습니다.

**Comment by seonghwan7694** [comment]
![7326004_1.jpg](https://user-images.githubusercontent.com/93508637/206620264-57e9d52d-7e0d-457a-8e3c-17c5462a5204.jpg)
