### ISSUE TITLE
지금까지 제작한 사이트 SvelteKit 써서 구현해봤습니다

### ISSUE THREAD

**Issue by krome0** [krome0/universal-kiosk#14]
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/37375701/206843226-41d9e5d9-478c-4a3f-92fd-204835cff1aa.png">

a4b05c7f4c20b9680767b7064cf4259eb537b551

fetch로 서버에서 json 데이터 받아서 상품 항목 추가 + 상품 항목 토글해서 가격 올라/내려가는거까지 구현했습니다.

**Comment by seonghwan7694** [comment]
확인해보겠습니다.

**Comment by seonghwan7694** [comment]
nodejs, npm 버전 맞추느라 시간 다 잡아먹었네요.. 장고 -> 스벨트킷(뭔진 모름)으로 바꾸신것 같은데, CSS가 좀 깨지네요. 수정해서 커밋하면 될까요?

![image](https://user-images.githubusercontent.com/93508637/206856888-4096f4da-4e0a-4f95-b630-b7ed866aabca.png)
저는 저런 클래스(s- 로 시작하는 거)를 사용한 적이 없는데, 자동으로 넣어진 건가요?

**Comment by krome0** [comment]
> nodejs, npm 버전 맞추느라 시간 다 잡아먹었네요.. 장고 -> 스벨트킷(뭔진 모름)으로 바꾸신것 같은데, CSS가 좀 깨지네요. 수정해서 커밋하면 될까요?

넵 깨지는 부분이 있으면 수정해서 커밋해주시면 감사하겠습니다.

> ![image](https://user-images.githubusercontent.com/93508637/206856888-4096f4da-4e0a-4f95-b630-b7ed866aabca.png) 저는 저런 클래스(s- 로 시작하는 거)를 사용한 적이 없는데, 자동으로 넣어진 건가요?

일단 코드에는 header_container로 넣어놨는데 s-같은거는 자동으로 생성된거 같네요

**Comment by seonghwan7694** [comment]
파일 위치 : 
![image](https://user-images.githubusercontent.com/93508637/206857936-240498b5-5e03-4606-aa4f-eb6569b83389.png)

혹시 라벨 태그 <label></label> 의도해서 넣으신건가요? 이것때문에 가운데 정렬이 안 먹혔어요. label에 클래스 붙여주면 되긴하는데 안 예뻐서 음..
![image](https://user-images.githubusercontent.com/93508637/206857920-da3c8ba7-aa8d-4351-8984-9138da4894b9.png)

그리고 기존에 있던 체크박스가 hidden 처리되어있는것 같은데 이것도 의도하신걸까요??

**Comment by krome0** [comment]
> 파일 위치 : ![image](https://user-images.githubusercontent.com/93508637/206857936-240498b5-5e03-4606-aa4f-eb6569b83389.png)
> 
> 혹시 라벨 태그 의도해서 넣으신건가요? 이것때문에 가운데 정렬이 안 먹혔어요. label에 클래스 붙여주면 되긴하는데 안 예뻐서 음.. ![image](https://user-images.githubusercontent.com/93508637/206857920-da3c8ba7-aa8d-4351-8984-9138da4894b9.png)
> 
> 그리고 기존에 있던 체크박스가 hidden 처리되어있는것 같은데 이것도 의도하신걸까요??

label 태그로 감싸고 안에 hidden 처리된 체크박스를 넣어서 커피 상품 목록 자체가 체크박스가 되게 만든건데... 혹시 다른 방법이 있을까요?

**Comment by seonghwan7694** [comment]
아하 그 용도였군요 label 태그를 이렇게 사용할 수도 있네요.. 배워갑니다...

![image](https://user-images.githubusercontent.com/93508637/206858997-79d6d0cd-688a-4dfc-82e2-29fa06b479e7.png)

이렇게 바깥쪽 div를 삭제하고 label에 클래스를 넣어주면 되네요. (아래는 결과)

![image](https://user-images.githubusercontent.com/93508637/206859036-dbb09337-4ae4-4c51-9fce-028d0f8b1fce.png)

아래쪽 진한 남색이 적용 안되는것만 해결하고 마무리(커밋)하겠습니다.

**Comment by seonghwan7694** [comment]
아 이해했습니다.
> label 태그로 감싸고 안에 hidden 처리된 체크박스를 넣어서 커피 상품 목록 자체가 체크박스가 되게 만든건데
추가적으로 hover? 인가 activated? 인가 넣어줘서 선택되었다는걸 UI로 나타내보겠습니다.

**Comment by seonghwan7694** [comment]
[ff8afa2](https://github.com/krome0/universal-kiosk/commit/ff8afa210e6e7c5d77f1fdc033de33db38468a40)

최대한 적은 코드로 수정하려고 노력했습니다.

label 태그의 경우, 겉에 있던 div 태그를 삭제하고 label 태그에 div태그에 있었던 클래스를 넣어주었습니다.
