### ISSUE TITLE
웹사이트 배포 관련

### ISSUE THREAD

**Issue by krome0** [krome0/universal-kiosk#15]
## 선택지
* Netlify
* front-end용 리포지토리 파서 Github Pages 사용
* 개인 서버에서 열기

이렇게 선택지가 있어보이는데 어떤 방식이 가장 나을까요?

**Comment by seonghwan7694** [comment]
* Netlify
> 이게 좋을 것 같습니다.
* front-end용 리포지토리 파서 Github Pages 사용
> 깃허브 아이디 공개하는게 좀 꺼려져서 이건 피하면 좋을 것 같습니다. 아무래도 [github ID].github.io 라는게 보이는 것 같아서요. [github ID].github.io 라는 주소가 안 뜨는 방법이 있다면 이 방법이 좋을 것 같은데..
* 개인 서버에서 열기
> 이전에 올려주신 #13 이거 말하는건가요? 담백하니 이 방법도 저는 좋습니다.

결론 : Netlify > 개인 서버에서 열기 > Github Pages 사용

**Comment by krome0** [comment]
> * Netlify
> 
> > 이게 좋을 것 같습니다.
> 
> * front-end용 리포지토리 파서 Github Pages 사용
> 
> > 깃허브 아이디 공개하는게 좀 꺼려져서 이건 피하면 좋을 것 같습니다. 아무래도 [github ID].github.io 라는게 보이는 것 같아서요. [github ID].github.io 라는 주소가 안 뜨는 방법이 있다면 이 방법이 좋을 것 같은데..
> 
> * 개인 서버에서 열기
> 
> > 이전에 올려주신 #13 이거 말하는건가요? 담백하니 이 방법도 저는 좋습니다.
> 
> 결론 : Netlify > 개인 서버에서 열기 > Github Pages 사용

한번 Netlify로 배포 시도해보겠습니다

**Comment by seonghwan7694** [comment]
1번째, 3번째 선택지 모두 성공하셨네요. 수고하셨습니다아~
