### ISSUE TITLE
깃허브 액션 설정해서 커밋해도 될까요?

### ISSUE THREAD

**Issue by seonghwan7694** [krome0/universal-kiosk#18]
이산수학 한 4시간 공부하면 끝마칠것같기도하고 제가 한게 없는 것 같아 죄책감을... ㅎㅎㅎ

제가 접근할 수 있는게 아닌지라 아래 3개가 설정되어있어야합니당
![image](https://user-images.githubusercontent.com/93508637/207410066-87d43550-53bf-42d7-a8b5-393b83e9627d.png)

GH_TOKEN : [링크](https://github.com/settings/tokens/new)에서 발급받기, 아래에서 repo, workflow 부분만 선택하시고 토큰 이름은 아무거나 괜찮습니다.

![image](https://user-images.githubusercontent.com/93508637/207411130-c905fa9c-de08-4d11-b41b-dd383fe863af.png)

NETFLIFY_SITE_ID : 아래 사진에서 site id 부분
![image](https://user-images.githubusercontent.com/93508637/207411488-7062e7fe-271e-4ea3-8236-d81e7066dfaa.png)

NETFLIFY_AUTH_TOKEN : 아래 사진에서 New access token 하고 발급받기
![image](https://user-images.githubusercontent.com/93508637/207412049-e986673e-e058-4cc6-8340-19bb1baf3e7e.png)

위 3개를 설정해주시면 감사하겠습니다.

**Comment by seonghwan7694** [comment]
음 생각해보니 도커 쓰셔서 하셨으면 이 방법은 버리신건가...

**Comment by seonghwan7694** [comment]
음 걍 로컬에서 테스트해봐서 PR날릴수 있으면 날려보겠습니다.

**Comment by krome0** [comment]
제가 어제 몇가지 읽어보니까 

1. Netlify에서 build + deploy 방식
2. gh action에서 build + netlify에서 deploy 방식

이 두개가 있는거 같은데 일단 저는 첫번째 방법으로 설정해놨습니다. 
푸시하면 Netlify에서 자동으로 build하고 다시 deploy하는게 일단 gh action이랑 거의 동일하게 작동하는거 같아서 놔뒀어요

*처음에는 gh action으로 해보려고 했는데 자꾸 page not found 떠서 그냥 일단 netlify로 해놨습니다

**Comment by seonghwan7694** [comment]
오 성공했슴다 PR 날릴께요..

**Comment by seonghwan7694** [comment]
날렸습니다 #20

**Comment by krome0** [comment]
merge 했습니다

**Comment by krome0** [comment]
확인해봤는데 kiosk.krome0.com은 제대로 작동하는데 원본 url로 들어가면 page not found가 뜨네요...

**Comment by seonghwan7694** [comment]
원본 url로 들어가면 page not found가 뜬다는게 어떤 의미인가요?
![image](https://user-images.githubusercontent.com/93508637/207434230-b22e9138-3dc2-41e5-8715-84fa29eb56e0.png)
이거 말씀하시는걸까요...? kiosk.krome0.com 만 잘 작동하면 되는거 아닌가요??

**Comment by seonghwan7694** [comment]
아 잠시만요.. 그때문인지는 아닌 것 같은데 실수를했네요.. 잠시만요

**Comment by seonghwan7694** [comment]
음...? 정말 깨졌네요....

**Comment by krome0** [comment]
일단 임시로 netlify에서 수동 deploy 했습니다

**Comment by seonghwan7694** [comment]
아 해결했습니다
![image](https://user-images.githubusercontent.com/93508637/207438074-9fb47b05-d754-478b-9c3e-4be0ee7891dd.png)
이거 액티브로 해야하는것같습니다.
