### ISSUE TITLE
버튼 선택시 선택 효과 + hover 효과 + 셀레니움 버튼 선택까지 완벽하게 작동합니다

### ISSUE THREAD

**Issue by krome0** [krome0/universal-kiosk#19]
시간 남으면 결제(or 영수증) 화면 + 그 화면에서 처음 화면으로 돌아가는거 까지 한번 만들어 보겠습니다

**Comment by krome0** [comment]
ESP-NOW 코드도 일단은 다 짜놨습니다.
내일 창공 전시 전에 테스트만 한번 해보면 될 것 같네요

**Comment by seonghwan7694** [comment]
헉 수고하셨습니다 🤩

**Comment by seonghwan7694** [comment]
저희 QR코드 바꿔야할것같아요
