### ISSUE TITLE
사용한 이미지를 올려주세요.

### ISSUE THREAD

**Issue by seonghwan7694** [krome0/universal-kiosk#5]
<h1>.webp 형식이 아닌 .svg, .png 등의 형식으로 올려주세요</h1>

<h2>문제점</h2>

> 아래에서 '포장', '매장'에 해당하는 이미지가 없습니다. 

![image](https://user-images.githubusercontent.com/93508637/205450144-66f944a4-6315-4321-b7fb-0cf68b5a967d.png)

<h2>문제점</h2>

> 아래에서 'LOGO', '장바구니'에 해당하는 이미지가 없습니다. 추가적으로, 급한건 아니지만 판매할 물건을 고르고 이미지를 정해야합니다.
> 회색부분이 정사각형이 아니라 직사각형인게 별로긴한데.. 일단 가만히 두겠습니다.

![image](https://user-images.githubusercontent.com/93508637/205450164-25697a3a-ab7e-4911-8030-318ebb524bb6.png)

**Comment by krome0** [comment]
design 폴더에 올렸습니다
